name: Build and Release Electron App for Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Set up pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Build Electron app
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: pnpm run build

    - name: Publish Electron app
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: pnpm run publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-windows
        path: release/${{ github.ref_name }}/**/*.exe
